### ISSUE TITLE
步骤疑问

### ISSUE THREAD

**Issue by wjq1981** [yuanw-18/Allo4D#1]
您好，我就用中文提问吧。我看您这个工具需要用到pep和cds，意思是组装后直接基因注释，然后用得到的pep和cds再回来去分型，然后挂载吗？

**Comment by yuanw-18** [comment]
感谢您的提问~ 
是对组装好的基因组进行分型，可以是染色体水平，也可以是非染色体水平，用注释得到的pep和cds对已有的染色体或者scaffold或者contig进行分型。如您想提高基因组的连续性，比如将scaffold水平的基因组提升至染色体水平，可使用[RagTag](https://github.com/malonge/RagTag)，将该基因组挂载到其近缘物种染色体水平的基因组上提升其连续性。

**Comment by wjq1981** [comment]
好的谢谢，我大概明白了
