### ISSUE TITLE
区分异源同源多倍体染色体组为B1B1B2B2B2B2

### ISSUE THREAD

**Issue by z626093820** [yuanw-18/Allo4D#2]
老师，您好，这个软件能够区分染色体组为B1B1B2B2B2B2的6倍体吗？

**Comment by yuanw-18** [comment]
不可以，只针对异源四倍体

**Comment by HorticLee** [comment]
> 老师，您好，这个软件能够区分染色体组为B1B1B2B2B2B2的6倍体吗？

或许可以参考最新发表在Molecular Plant上的六倍体甘薯起源与进化文章。
Haplotype-based phylogenetic analysis and population genomics uncover the origin and domestication of sweetpotato
