### ISSUE TITLE
Allo4Dalign.py FilterBlastp error

### ISSUE THREAD

**Issue by HorticLee** [yuanw-18/Allo4D#3]
您好，我在运行第1步时遇到一个问题。
命令行如下：
python $scriptdir/Allo4Dalign.py -thread 40 \
 -sp4pep Ar.pep -sp2pep Bv.pep.fa \
 -sp4bed Ar.bed -sp2bed Bv.bed \
 -sp4cds Ar.cds
**报错如下：**
Traceback (most recent call last):
  File "/Allo4D-main/script/Allo4Dalign.py", line 55, in <module>
    FilterBlastp(path1 + "/sp4_sp2.blast",path1 + "/sp4_sp2.blast.filter")
  File "Allo4D-main/script/Allo4Dalign.py", line 45, in FilterBlastp
    **len1 = peplen_dict[str(line[0])]; len2 = peplen_dict[str(line[1])]**
                                             ~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'ARR21801'
**结果文件：**
1.Collinear/
├── Ar.pep.db.pdb
├── Ar.pep.db.phr
├── Ar.pep.db.pin
├── Ar.pep.db.pog
├── Ar.pep.db.pos
├── Ar.pep.db.pot
├── Ar.pep.db.psq
├── Ar.pep.db.ptf
├── Ar.pep.db.pto
├── sp4_sp2.blast
├── sp4_sp2.blast.filter
└── sp4_sp4.blast
其中，sp4_sp2.blast.filter为0，空文件

看起来似乎是blast.filter过滤哪一步有问题，想请教一下

**Comment by yuanw-18** [comment]
可以发一点测试数据给我吗？[wangy959@mail3.sysu.edu.cn](mailto:wangy959@mail3.sysu.edu.cn)，可以邮件沟通

**Comment by HorticLee** [comment]
> 可以发一点测试数据给我吗？[wangy959@mail3.sysu.edu.cn](mailto:wangy959@mail3.sysu.edu.cn)，可以邮件沟通

好的，谢谢！
